### ISSUE TITLE
[모던 자바 인 액션] 함수형 프로그래밍

### ISSUE THREAD

**Issue by eastheat10** [Java-Awesome/Javawesome_reading_book#10]
# 함수형 프로그래밍

명령형 (절차지향, 객체지향) / 선언형 (함수형)

![fp](https://nesoy.github.io/assets/logo/FP.png)

프로그래밍의 언어나 방식이 아닌 사고방식을 배우는 것 (ex. 객체지향 프로그래밍)

### 1. 1급 객체

* 변수나 자료구조에 담을 수 있다.
* 파라미터로 전달 가능
* 반환값으로 사용가능

> 자바에서는 객체가 위 기능을 수행했다. 자바8부터 함수를 일급객체로 사용가능.
>
> Function이 일급 객체로 사용되는 언어를 **First-class function**를 지원하는 언어라고 한다.

### 2. 고차 함수 (High-Order Function)

* 함수에 함수를 파라미터로 전달할 수 있다.
* 함수의 반환값으로 함수를 사용할 수 있다.

### 3. 불변성 (Immutability)

* 함수형 프로그래밍에서는 데이터가 변할 수 없는데, 이를 불변성 데이터라고 한다.
* 데이터 변경이 필요한 경우, 원본 데이터 구조를 변경하지 않고 그 데이터를 복사본을 만들어 그 일부를 변경하고, 변경한 복사본을 사용해 작업을 진행한다.

### 4. 순수 함수 (Pure Function)

* 동일한 입력에는 항상 같은 값 반환
* Side Effect가 없어햐 한다. (함수 내부에서 인자의 값을 변경하거나 프로그램의 상태를 변경하는 것)

>  순수 함수를 호출하면 프로그램에 변화가 없고, 입력 값에 대한 결과를 예상할  수 있어서 테스트하기 쉽다.

#### 클로저 (closure)

* 함수 내부의 지역변수가 사라지지 않고 계속해서 값을 유지하는 상태

```java
public class Main {
    public static void main(String[] args) throws IOException {
        Supplier<String> m = outter();
        System.out.println(m.get());
    }

    private static Supplier<String> outter() {
        String s = "hello";
        return () -> s;
    }
 }
```

`main`함수의 지역변수인 m에 `outter()` 를 대입했다. 지역변수 m은 `outter()`가 종료되었지만, `outter()`의 지역변수 `s`에 접근할 수 있다.

클로저는 외부함수(`outter`)는 외부함수의 지역변수를 사용하는 내부함수(`main`)가 소멸될 때 까지 소멸되지 않는 특성을 의미한다.

외부함수의 지역변수는 **final**이어야 하지만, 자바8에서는 **effectively final**이라는 개념을 도입해 해당 변수가 변경되지 않는다고 컴파일러가 판단하여 final로 해석한다.

> [함수형프로그래밍 - 출처](https://velog.io/@kyusung/%ED%95%A8%EC%88%98%ED%98%95-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D-%EC%9A%94%EC%95%BD)
>
> [클로저 - 출처](https://velog.io/@janeljs/Java-Closure)

**Comment by her0807** [comment]
고생했어요 제코 :)

**Comment by hyeonic** [comment]
굳 명쾌한 설명 감사합니다
