### ISSUE TITLE
[모던 자바 인 액션] distinct 사용

### ISSUE THREAD

**Issue by eastheat10** [Java-Awesome/Javawesome_reading_book#16]
# 소개
> 제목 : 
책 페이지 : p163
내용: 
```java
List<String> words = Arrays.asList("Hello", "World");
words.stream()
  .map(word -> word.split(""))
  .distinct()
  .collect(toList());

for (String[] strings : collect) {
    for (String string : strings) {
        System.out.print(string + " ");
    }
    System.out.println();
}
/*
H e l l o 
W o r l d 
*/
```
여기서 `distinct()`를 사용해도 같은 문자가 구분되지 않는 이유가 hashcode가 달라서 그런건가요?

**Comment by hyeonic** [comment]
`.map(word -> word.split("")`이 문자열을 문자열 배열로 바꿔줘서 그런것 같습니다.

`String[] {"H", "e", "l", "l", "o"} == String[] {"W", "o", "r", "l" ,"d"}`

이렇게 비교하는 꼴이라 책 뒤에 서술된 `flatMap`을 사용하면 의도한 대로 동작할 것 같네요!

**Comment by her0807** [comment]
### distinct 메서드 내부 구조
<img width="311" alt="스크린샷 2021-11-25 오후 9 40 14" src="https://user-images.githubusercontent.com/26570275/143443761-35d53eda-7983-4f6e-b669-fc923e149a01.png">

위를 보시면 메서드 내부에서 스트림을 받아서 처리하기 때문에 스트림이 아닌 경우는 중복 제거하는 로직이 수행되지 않습니다.

### flatMap 내부 구조
<img width="768" alt="스크린샷 2021-11-25 오후 9 44 39" src="https://user-images.githubusercontent.com/26570275/143444397-bb30df29-adba-4f50-b731-b133f02f71a5.png">
flatMap 을 사용하여 배열을 새로운 스트림으로 변환하여 사용 할 수 있습니다.

### 사용 예시






```java
위에 map(word -> word.split("")) -> flatMap(Arrays::stream) 으로 바꾸면 잘 동작합니다~ 
```
