### ISSUE TITLE
6.2.3 예제 코드 관련 질문

### ISSUE THREAD

**Issue by hyeonic** [Java-Awesome/Javawesome_reading_book#20]
# 소개
> 제목 : 6.2.3 예제 코드 관련 질문
책 페이지 : 205p
내용: 책에 기재된 예제를 작성하는데 의도와는 다르게 컴파일 에러를 발생 시킨다.
---

# 6.2.3 예제 코드 관련 질문

```java
String shortMenu = menu.stream().map(Dish::getName).collect(joining());
```

joining 메서드는 내부적으로 StringBuilder를 이용해서 문자열을 하나로 만든다. Dish 클래스가 요리명을 반환하는 toString 메서드를 포함하고 있다면 다음 코드에서 보여주는 것 처럼 map으로 각 요리의 이름을 추출하는 과정을 생략할 수 있다.

toString 메서드를 포함하는 Dish 클래스이다.
```java
public class Dish {
    private final String name;
    private final boolean vegetarian;
    private final int calories;
    private final Type type;
    ... 
    @Override
    public String toString() {
        return name;
    }
    ...
}
```

```java
String shortMenu = menu.stream().collect(joining());
```

하지만 생략 시 컴파일 에러를 발생 시킨다. 

![image](https://user-images.githubusercontent.com/59357153/144172964-3084818a-60e7-484e-8ae5-43ccc2c23fd6.png)

**Comment by her0807** [comment]
안녕하세요 혀닉!

<img width="792" alt="스크린샷 2021-12-01 오후 2 22 17" src="https://user-images.githubusercontent.com/26570275/144176654-9b094f01-8b4f-4a08-aafc-c9cd8a389332.png">

위와 같은 에러는 예제에서 표시할 때 `Collectors` 를 생략하고 예제를 작성해서 그렇습니다! 
collect 최종 연산을 수행하려면, 내부에 어떤 방식으로 연산을 수행할지, 어떤 반환값을 가질건지 정의된 Collector 를 같이 보내줘야하거든요.

관련 내용을 [이슈](https://github.com/Java-Awesome/Javawesome_reading_book/issues/21)에 정리해두었습니다.

참고하여 해결해보세요 :)

**Comment by hyeonic** [comment]
이미 `import static` 을 이용해서 작성한 상태입니다!
![image](https://user-images.githubusercontent.com/59357153/144177761-258da23f-60f6-4a3c-a4b7-a5e9d86ded9c.png)

명시적으로 작성해도 동일하네요 ㅜㅠ
![image](https://user-images.githubusercontent.com/59357153/144177831-c89ca5d3-2573-4dda-8c89-e244f179e311.png)
