### ISSUE TITLE
대표적인 Java 코딩 컨벤션에 대해 알아보자. 

### ISSUE THREAD

**Issue by her0807** [Java-Awesome/Javawesome_reading_book#27]
# 소개
> 제목 : 가독성을 향상시키는 방법
책 페이지 :9장 전범위 p
내용: 
자바 문법 중에서도 네이밍에 관한 부분을 조금 더 추가했다. 
---

### 2.4. 패키지 이름은 소문자로 구성
[package-lowercase]

패키지 이름은 소문자를 사용하여 작성한다. 단어별 구문을 위해 언더스코어(_)나 대문자를 섞지 않는다.

`나쁜 예`
```
package com.navercorp.apiGateway

package com.navercorp.api_gateway
```

`좋은 예`
```
package com.navercorp.apigatewa
```

### 2.6. 클래스 이름에 명사 사용
[class-noun]

클래스 이름은 `명사나 명사절`로 짓는다.

명사절이란「주어+동사」를 갖추어 문장 형태를 이루고 있다. 문장 내에서 명사, 형용사, 부사 등의 구실을 하는 구문으로서 문장 가운데 포함된「작은 문장」이라고 할 수 있는 것이다.

### 2.7. 인터페이스 이름에 명사/형용사 사용
[interface-noun-adj]

인터페이스(interface)의 이름은 클래스 이름은 `명사/명사절로` 혹은` 형용사/형용사절`로 짓는다.

`좋은 예`
```
public interface RowMapper {

public interface AutoClosable {
```

### 명사 어미
`-ion, -sion, --tion -ness -age -ship -ance, -ence, -ency, -ment,`

`-ion, -sion, --tion :..하는 행위, ..하는 상태,..의 결과`
act 행하다 => action 활동
 object 반대하다 => objection 반대,

`-ness :..하는 상태`
careless 부주의한 => carelessness 부주의
dark 어두운 => darkness 어둠

`-age : ..하는 행위, 상태`
carriage 차, courage 용기

`-ship : ..의 상태,  기술, 권위, 직업`
hard 어려운 => hardship 고난
friend 친구 => friendship 우정,

`-ance, -ence, -ency : ..의 상태, 행위, 과정`
important 중요한 => importance 중요
differ 다르다 => difference 차이
 
`-ment : ..하는 상태, 행위, 결과`
achieve 성취하다 => achievement 업적, 

### 명사 && 형용사 어미
`-ery ,-ory, -ity, -ty, -dom, -ar, -er, -or, -an, -ian, -cian, -ist`

`-ary, -ery ,-ory : ..과 관련이 있는,..을 하는 장소`
library 도서관, dictionary 사전

`-ar, -er, -or : ..하는 사람 혹은 사물`
lie 거짓말하다 => liar 거짓말장이
bake 굽다 => baker 빵 제조업자
buy 사다 => buyer 구매자
foreign 외국의 => foreigner 외국인

`-an, -ian : ..에 사는 사람`

Korea 한국 => Korean 한국인, 
taly 이탈리아 => Italian 이탈리아인

 
`-cian : ..의 기술을 가진 사람`

music 음악 => musician 음악인
technic 기술 => technician 기술자
 

`-ist :..하는 사람`
art 예술 => artist 예술가
biology 생물 => biologist  생물학자

`-less : ..이 없이`
base 기초 => baseless 기반이 없는
 care 주의 => careless 부주의한

### 형용사 어미
`-y, -less, -ly(형용사, 부사), -ful, -able, -ible, -al, -ous, -ive, -ish,`

`-y : ..하는 경향이 있는`
air 공기 => airy 바람이 잘 통하는
cloud 구름 => cloudy 구름낀

`-ful : ..이 가득한, 많은 상태`
beauty 아름다움 => beautiful 아름다운,
care 조심 => careful 조심스러운

### 2.10. 메서드 이름은 동사/전치사로 시작
[method-verb-preposition]

메서드명은 기본적으로는 동사로 시작한다. 

다른 타입으로 전환하는 메서드나 빌더 패턴을 구현한 클래스의 메서드에는 전치사를 쓸 수 있다.

`좋은 예`
동사사용 : renderHtml()

전환메서드의 전치사 : toString()

Builder 패턴 적용한 클래스의 메서드의 전치사 : withUserId(String id)

### 3.3. 제한자 선언의 순서
[modifier-order]

클래스/메서드/멤버변수의 제한자는 Java Language Specification에서 명시한 아래의 순서로 쓴다.

public
protected
private
 abstract
 static
 final

### 7.3. 메소드 사이에 빈 줄 삽입
[blankline-between-methods]

메서드의 선언이 끝난 후 다음 메서드 선언이 시작되기 전에 빈줄을 삽입한다.

`좋은 예`
public void setId(int id) {
    this.id = id;
}

public void setName(String name) {
    this.name = name;
}

## References
- [명사절](https://english-mint.tistory.com/entry/%EB%AA%85%EC%82%AC%EC%A0%88%EC%9D%B4%EB%9E%80-%EC%98%88%EB%AC%B8%EC%9D%84-%ED%86%B5%ED%95%B4-%EB%9C%BB%EC%9D%84-%EC%95%8C%EC%95%84%EB%B3%B4%EC%9E%90)
- [네이버 코딩 컨밴션](https://naver.github.io/hackday-conventions-java)
-

**Comment by eastheat10** [comment]
놓치기 쉽지만 중요한 부분 같습니다.
