### ISSUE TITLE
[모던 자바 인 액션] 람다 질문입니다

### ISSUE THREAD

**Issue by her0807** [Java-Awesome/Javawesome_reading_book#9]
# 소개
> 제목 :  예제를 이해한게 맞는지? 
책 페이지 : 96 p
내용: 퀴 즈 3-3 문제에 아래와 같이 나와있는데. 반환 값이 Apple 이 아니라. Integer 라서 람다의 잘못된 예제인건가..?
---
```java
Predicate<Apple> p = (Apple a) -> a, getWeight(); 
```

**Comment by eastheat10** [comment]
Predicate의 함수 디스크럽트는 T -> boolean 입니다.

예제에서는 Integer를 반환하기 때문에 잘못되었습니다.
